In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler


# Φόρτωμα CSV αρχείου
df = pd.read_csv('books_1.Best_Books_Ever.csv', sep=',')

# Βλέπουμε τα δεδομένα
print(df.head())  # Βλέπουμε τις πρώτες 5 γραμμές
print(df.info())  # Παίρνουμε τους τύπους των δεδομένων και πληροφορίες για τα null values
print(df.describe())  # Βλέπουμε τα στατιστικά των δεδομένων

                                        bookId  \
0                     2767052-the-hunger-games
1  2.Harry_Potter_and_the_Order_of_the_Phoenix
2                   2657.To_Kill_a_Mockingbird
3                     1885.Pride_and_Prejudice
4                               41865.Twilight

                                       title                 series  \
0                           The Hunger Games    The Hunger Games #1
1  Harry Potter and the Order of the Phoenix        Harry Potter #5
2                      To Kill a Mockingbird  To Kill a Mockingbird
3                        Pride and Prejudice                    NaN
4                                   Twilight   The Twilight Saga #1

                                      author  rating  \
0                            Suzanne Collins    4.33
1  J.K. Rowling, Mary GrandPré (Illustrator)    4.50
2                                 Harper Lee    4.28
3  Jane Austen, Anna Quindlen (Introduction)    4.26
4                            Stephenie Meyer    3.60

                                         description language           isbn  \
0  WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...  English  9780439023481
1  There is a door at the end of a silent corrido...  English  9780439358071
2  The unforgettable novel of a childhood in a sl...  English  9999999999999
3  Alternate cover edition of ISBN 9780679783268S...  English  9999999999999
4  About three things I was absolutely positive.\...  English  9780316015844

                                              genres  \
0  ['Young Adult', 'Fiction', 'Dystopia', 'Fantas...
1  ['Fantasy', 'Young Adult', 'Fiction', 'Magic',...
2  ['Classics', 'Fiction', 'Historical Fiction', ...
3  ['Classics', 'Fiction', 'Romance', 'Historical...
4  ['Young Adult', 'Fantasy', 'Romance', 'Vampire...

                                          characters  ... firstPublishDate  \
0  ['Katniss Everdeen', 'Peeta Mellark', 'Cato (H...  ...              NaN
1  ['Sirius Black', 'Draco Malfoy', 'Ron Weasley'...  ...         06/21/03
2  ['Scout Finch', 'Atticus Finch', 'Jem Finch', ...  ...         07/11/60
3  ['Mr. Bennet', 'Mrs. Bennet', 'Jane Bennet', '...  ...         01/28/13
4  ['Edward Cullen', 'Jacob Black', 'Laurent', 'R...  ...         10/05/05

                                              awards numRatings  \
0  ['Locus Award Nominee for Best Young Adult Boo...    6376780
1  ['Bram Stoker Award for Works for Young Reader...    2507623
2  ['Pulitzer Prize for Fiction (1961)', 'Audie A...    4501075
3                                                 []    2998241
4  ['Georgia Peach Book Award (2007)', 'Buxtehude...    4964519

                                      ratingsByStars likedPercent  \
0  ['3444695', '1921313', '745221', '171994', '93...         96.0
1  ['1593642', '637516', '222366', '39573', '14526']         98.0
2  ['2363896', '1333153', '573280', '149952', '80...         95.0
3  ['1617567', '816659', '373311', '113934', '767...         94.0
4  ['1751460', '1113682', '1008686', '542017', '5...         78.0

                                             setting  \
0  ['District 12, Panem', 'Capitol, Panem', 'Pane...
1  ['Hogwarts School of Witchcraft and Wizardry (...
2               ['Maycomb, Alabama (United States)']
3  ['United Kingdom', 'Derbyshire, England (Unite...
4  ['Forks, Washington (United States)', 'Phoenix...

                                            coverImg  bbeScore bbeVotes  price
0  https://i.gr-assets.com/images/S/compressed.ph...   2993816    30516   5.09
1  https://i.gr-assets.com/images/S/compressed.ph...   2632233    26923   7.38
2  https://i.gr-assets.com/images/S/compressed.ph...   2269402    23328    NaN
3  https://i.gr-assets.com/images/S/compressed.ph...   1983116    20452    NaN
4  https://i.gr-assets.com/images/S/compressed.ph...   1459448    14874    2.1

[5 rows x 25 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52478 entries, 0 to 52477
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   bookId            52478 non-null  object
 1   title             52478 non-null  object
 2   series            23470 non-null  object
 3   author            52478 non-null  object
 4   rating            52478 non-null  float64
 5   description       51140 non-null  object
 6   language          48672 non-null  object
 7   isbn              52478 non-null  object
 8   genres            52478 non-null  object
 9   characters        52478 non-null  object
 10  bookFormat        51005 non-null  object
 11  edition           4955 non-null   object
 12  pages             50131 non-null  object
 13  publisher         48782 non-null  object
 14  publishDate       51598 non-null  object
 15  firstPublishDate  31152 non-null  object
 16  awards            52478 non-null  object
 17  numRatings        52478 non-null  int64
 18  ratingsByStars    52478 non-null  object
 19  likedPercent      51856 non-null  float64
 20  setting           52478 non-null  object
 21  coverImg          51873 non-null  object
 22  bbeScore          52478 non-null  int64
 23  bbeVotes          52478 non-null  int64
 24  price             38113 non-null  object
dtypes: float64(2), int64(3), object(20)
memory usage: 10.0+ MB
None
             rating    numRatings  likedPercent      bbeScore      bbeVotes
count  52478.000000  5.247800e+04  51856.000000  5.247800e+04  52478.000000
mean       4.021878  1.787865e+04     92.231545  1.984023e+03     22.529003
std        0.367146  1.039448e+05      5.990689  3.515314e+04    369.158541
min        0.000000  0.000000e+00      0.000000  0.000000e+00     -4.000000
25%        3.820000  3.410000e+02     90.000000  8.400000e+01      1.000000
50%        4.030000  2.307000e+03     94.000000  9.700000e+01      1.000000
75%        4.230000  9.380500e+03     96.000000  1.870000e+02      2.000000
max        5.000000  7.048471e+06    100.000000  2.993816e+06  30516.000000

In [17]:
#1. 

# Έλεγχος για τιμ΄ές που λείπουν στα δεδομένα
missing_values = df.isnull().sum()
print(missing_values)

# Διαγραφή των σειρών με τις μη υπάρχουσες τιμές (NaN)
df = df.dropna()

bookId                  0
title                   0
series              29008
author                  0
rating                  0
description          1338
language             3806
isbn                    0
genres                  0
characters              0
bookFormat           1473
edition             47523
pages                2347
publisher            3696
publishDate           880
firstPublishDate    21326
awards                  0
numRatings              0
ratingsByStars          0
likedPercent          622
setting                 0
coverImg              605
bbeScore                0
bbeVotes                0
price               14365
dtype: int64

In [18]:
# Προεπεξεργασία 1.


# Create new columns with initial values set to 0
df['ratingByStars1'] = 0
df['ratingByStars2'] = 0
df['ratingByStars3'] = 0
df['ratingByStars4'] = 0
df['ratingByStars5'] = 0



# Update the corresponding new columns based on the list format of 'ratingsByStars'
for index, row in df.iterrows():
    ratings = row['ratingsByStars']
    if isinstance(ratings, list) and len(ratings) == 5:
        df.at[index, 'ratingByStars1'] = ratings[0]
        df.at[index, 'ratingByStars2'] = ratings[1]
        df.at[index, 'ratingByStars3'] = ratings[2]
        df.at[index, 'ratingByStars4'] = ratings[3]
        df.at[index, 'ratingByStars5'] = ratings[4]

# Print the updated DataFrame
print(df)

                                                 bookId  \
1           2.Harry_Potter_and_the_Order_of_the_Phoenix
8                     30.J_R_R_Tolkien_4_Book_Boxed_Set
29                                  375802.Ender_s_Game
37                                        17245.Dracula
42                            28187.The_Lightning_Thief
...                                                 ...
52135                         28637637-a-lady-unrivaled
52179      458341.Courtney_Crumrin_and_the_Night_Things
52232             12998057-captain-vorpatril-s-alliance
52263  808853.The_Complete_Adventures_of_Curious_George
52403                                      7199219-ed-n

                                                   title  \
1              Harry Potter and the Order of the Phoenix
8      J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...
29                                          Ender's Game
37                                               Dracula
42                                   The Lightning Thief
...                                                  ...
52135                                   A Lady Unrivaled
52179              Courtney Crumrin and the Night Things
52232                       Captain Vorpatril's Alliance
52263          The Complete Adventures of Curious George
52403                                               Edén

                                        series  \
1                              Harry Potter #5
8                   The Lord of the Rings #0-3
29                             Ender's Saga #1
37                                  Dracula #1
42          Percy Jackson and the Olympians #1
...                                        ...
52135                   Ladies of the Manor #3
52179                      Courtney Crumrin #1
52232  Vorkosigan Saga (Publication Order) #15
52263       Curious George Original Adventures
52403                                  Edén #1

                                                  author  rating  \
1              J.K. Rowling, Mary GrandPré (Illustrator)    4.50
8                                         J.R.R. Tolkien    4.60
29     Orson Scott Card, Stefan Rudnicki (Narrator), ...    4.30
37     Bram Stoker, Nina Auerbach (Editor), David J. ...    4.00
42                       Rick Riordan (Goodreads Author)    4.26
...                                                  ...     ...
52135               Roseanna M. White (Goodreads Author)    4.33
52179  Ted Naifeh (Goodreads Author), Kalah Allen (De...    4.06
52232            Lois McMaster Bujold (Goodreads Author)    4.21
52263                              Margret Rey, H.A. Rey    4.23
52403                                         Kioskerman    3.97

                                             description language  \
1      There is a door at the end of a silent corrido...  English
8      This four-volume, boxed set contains J.R.R. To...  English
29     Andrew "Ender" Wiggin thinks he is playing com...  English
37     You can find an alternative cover edition for ...  English
42     Alternate cover for this ISBN can be found her...  English
...                                                  ...      ...
52135  Lady Ella Myerston can always find a reason to...  English
52179  Presenting the initial COURTNEY CRUMRIN minise...  English
52232  Captain Ivan Vorpatril is happy with his relat...  English
52263  “This is George. He lived in Africa. He was a ...  English
52403  Recopilación de las tiras de Edén publicadas d...  Spanish

                isbn                                             genres  \
1      9780439358071  ['Fantasy', 'Young Adult', 'Fiction', 'Magic',...
8      9780345538376  ['Fantasy', 'Fiction', 'Classics', 'Adventure'...
29     9780812550702  ['Science Fiction', 'Fiction', 'Young Adult', ...
37     9780393970128  ['Classics', 'Horror', 'Fiction', 'Fantasy', '...
42     9780786838653  ['Fantasy', 'Young Adult', 'Mythology', 'Ficti...
...              ...                                                ...
52135  9780764213526  ['Historical Fiction', 'Christian Fiction', 'R...
52179  9781929998609  ['Graphic Novels', 'Comics', 'Fantasy', 'Horro...
52232  9781451638455  ['Science Fiction', 'Fiction', 'Space Opera', ...
52263  9780618164417  ['Childrens', 'Picture Books', 'Fiction', 'Cla...
52403  9789500730853  ['Comics', 'Graphic Novels', 'Graphic Novels C...

                                              characters  ...  \
1      ['Sirius Black', 'Draco Malfoy', 'Ron Weasley'...  ...
8      ['Frodo Baggins', 'Gandalf', 'Bilbo Baggins', ...  ...
29     ['Dink', 'Bernard', 'Valentine Wiggin', 'Peter...  ...
37     ['Jonathan Harker', 'Lucy Westenra', 'Abraham ...  ...
42     ['Annabeth Chase', 'Grover Underwood', 'Luke C...  ...
...                                                  ...  ...
52135  ['Ella Myerston', 'James Azerly', 'Susan Azerl...  ...
52179                                                 []  ...
52232                         ['Captain Ivan Vorpatril']  ...
52263                                                 []  ...
52403                                                 []  ...

                                                 setting  \
1      ['Hogwarts School of Witchcraft and Wizardry (...
8                                       ['Middle-earth']
29                                                    []
37     ['Transylvania (Romania)', 'Budapest (Hungary)...
42     ['New York City, New York (United States)', 'M...
...                                                  ...
52135                             ['Cotswolds, England']
52179                                                 []
52232                                                 []
52263                                                 []
52403                                                 []

                                                coverImg bbeScore bbeVotes  \
1      https://i.gr-assets.com/images/S/compressed.ph...  2632233    26923
8      https://i.gr-assets.com/images/S/compressed.ph...  1159802    12111
29     https://i.gr-assets.com/images/S/compressed.ph...   720651     7515
37     https://i.gr-assets.com/images/S/compressed.ph...   646782     6988
42     https://i.gr-assets.com/images/S/compressed.ph...   597132     6370
...                                                  ...      ...      ...
52135  https://i.gr-assets.com/images/S/compressed.ph...        8        1
52179  https://i.gr-assets.com/images/S/compressed.ph...        7        1
52232  https://i.gr-assets.com/images/S/compressed.ph...        6        1
52263  https://i.gr-assets.com/images/S/compressed.ph...        5        1
52403  https://i.gr-assets.com/images/S/compressed.ph...        2        1

       price ratingByStars1 ratingByStars2  ratingByStars3 ratingByStars4  \
1       7.38              0              0               0              0
8      21.15              0              0               0              0
29       4.6              0              0               0              0
37      4.55              0              0               0              0
42      1.79              0              0               0              0
...      ...            ...            ...             ...            ...
52135   6.42              0              0               0              0
52179   1.64              0              0               0              0
52232   5.51              0              0               0              0
52263   5.94              0              0               0              0
52403  15.00              0              0               0              0

       ratingByStars5
1                   0
8                   0
29                  0
37                  0
42                  0
...               ...
52135               0
52179               0
52232               0
52263               0
52403               0

[796 rows x 30 columns]

In [19]:
# Προεπεξεργασία 2.

# Create a new column 'genreSingle' with initial values set to None
df['genreSingle'] = None

# Update the 'genreSingle' column with the first item from the 'genres' list
for index, row in df.iterrows():
    genres = row['genres']
    if isinstance(genres, list) and len(genres) > 0:
        df.at[index, 'genreSingle'] = genres[0]

# Print the updated DataFrame
print(df)

                                                 bookId  \
1           2.Harry_Potter_and_the_Order_of_the_Phoenix
8                     30.J_R_R_Tolkien_4_Book_Boxed_Set
29                                  375802.Ender_s_Game
37                                        17245.Dracula
42                            28187.The_Lightning_Thief
...                                                 ...
52135                         28637637-a-lady-unrivaled
52179      458341.Courtney_Crumrin_and_the_Night_Things
52232             12998057-captain-vorpatril-s-alliance
52263  808853.The_Complete_Adventures_of_Curious_George
52403                                      7199219-ed-n

                                                   title  \
1              Harry Potter and the Order of the Phoenix
8      J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...
29                                          Ender's Game
37                                               Dracula
42                                   The Lightning Thief
...                                                  ...
52135                                   A Lady Unrivaled
52179              Courtney Crumrin and the Night Things
52232                       Captain Vorpatril's Alliance
52263          The Complete Adventures of Curious George
52403                                               Edén

                                        series  \
1                              Harry Potter #5
8                   The Lord of the Rings #0-3
29                             Ender's Saga #1
37                                  Dracula #1
42          Percy Jackson and the Olympians #1
...                                        ...
52135                   Ladies of the Manor #3
52179                      Courtney Crumrin #1
52232  Vorkosigan Saga (Publication Order) #15
52263       Curious George Original Adventures
52403                                  Edén #1

                                                  author  rating  \
1              J.K. Rowling, Mary GrandPré (Illustrator)    4.50
8                                         J.R.R. Tolkien    4.60
29     Orson Scott Card, Stefan Rudnicki (Narrator), ...    4.30
37     Bram Stoker, Nina Auerbach (Editor), David J. ...    4.00
42                       Rick Riordan (Goodreads Author)    4.26
...                                                  ...     ...
52135               Roseanna M. White (Goodreads Author)    4.33
52179  Ted Naifeh (Goodreads Author), Kalah Allen (De...    4.06
52232            Lois McMaster Bujold (Goodreads Author)    4.21
52263                              Margret Rey, H.A. Rey    4.23
52403                                         Kioskerman    3.97

                                             description language  \
1      There is a door at the end of a silent corrido...  English
8      This four-volume, boxed set contains J.R.R. To...  English
29     Andrew "Ender" Wiggin thinks he is playing com...  English
37     You can find an alternative cover edition for ...  English
42     Alternate cover for this ISBN can be found her...  English
...                                                  ...      ...
52135  Lady Ella Myerston can always find a reason to...  English
52179  Presenting the initial COURTNEY CRUMRIN minise...  English
52232  Captain Ivan Vorpatril is happy with his relat...  English
52263  “This is George. He lived in Africa. He was a ...  English
52403  Recopilación de las tiras de Edén publicadas d...  Spanish

                isbn                                             genres  \
1      9780439358071  ['Fantasy', 'Young Adult', 'Fiction', 'Magic',...
8      9780345538376  ['Fantasy', 'Fiction', 'Classics', 'Adventure'...
29     9780812550702  ['Science Fiction', 'Fiction', 'Young Adult', ...
37     9780393970128  ['Classics', 'Horror', 'Fiction', 'Fantasy', '...
42     9780786838653  ['Fantasy', 'Young Adult', 'Mythology', 'Ficti...
...              ...                                                ...
52135  9780764213526  ['Historical Fiction', 'Christian Fiction', 'R...
52179  9781929998609  ['Graphic Novels', 'Comics', 'Fantasy', 'Horro...
52232  9781451638455  ['Science Fiction', 'Fiction', 'Space Opera', ...
52263  9780618164417  ['Childrens', 'Picture Books', 'Fiction', 'Cla...
52403  9789500730853  ['Comics', 'Graphic Novels', 'Graphic Novels C...

                                              characters  ...  \
1      ['Sirius Black', 'Draco Malfoy', 'Ron Weasley'...  ...
8      ['Frodo Baggins', 'Gandalf', 'Bilbo Baggins', ...  ...
29     ['Dink', 'Bernard', 'Valentine Wiggin', 'Peter...  ...
37     ['Jonathan Harker', 'Lucy Westenra', 'Abraham ...  ...
42     ['Annabeth Chase', 'Grover Underwood', 'Luke C...  ...
...                                                  ...  ...
52135  ['Ella Myerston', 'James Azerly', 'Susan Azerl...  ...
52179                                                 []  ...
52232                         ['Captain Ivan Vorpatril']  ...
52263                                                 []  ...
52403                                                 []  ...

                                                coverImg bbeScore bbeVotes  \
1      https://i.gr-assets.com/images/S/compressed.ph...  2632233    26923
8      https://i.gr-assets.com/images/S/compressed.ph...  1159802    12111
29     https://i.gr-assets.com/images/S/compressed.ph...   720651     7515
37     https://i.gr-assets.com/images/S/compressed.ph...   646782     6988
42     https://i.gr-assets.com/images/S/compressed.ph...   597132     6370
...                                                  ...      ...      ...
52135  https://i.gr-assets.com/images/S/compressed.ph...        8        1
52179  https://i.gr-assets.com/images/S/compressed.ph...        7        1
52232  https://i.gr-assets.com/images/S/compressed.ph...        6        1
52263  https://i.gr-assets.com/images/S/compressed.ph...        5        1
52403  https://i.gr-assets.com/images/S/compressed.ph...        2        1

       price ratingByStars1 ratingByStars2 ratingByStars3  ratingByStars4  \
1       7.38              0              0              0               0
8      21.15              0              0              0               0
29       4.6              0              0              0               0
37      4.55              0              0              0               0
42      1.79              0              0              0               0
...      ...            ...            ...            ...             ...
52135   6.42              0              0              0               0
52179   1.64              0              0              0               0
52232   5.51              0              0              0               0
52263   5.94              0              0              0               0
52403  15.00              0              0              0               0

      ratingByStars5  genreSingle
1                  0         None
8                  0         None
29                 0         None
37                 0         None
42                 0         None
...              ...          ...
52135              0         None
52179              0         None
52232              0         None
52263              0         None
52403              0         None

[796 rows x 31 columns]

In [21]:
# Προεπεξεργασία 3.

# Assuming your data is stored in a DataFrame called 'df'
# You can read your data into the DataFrame using pandas, for example:
# df = pd.read_csv('your_data.csv')

# Convert 'publishDate' column to datetime format
# df['publishDate'] = pd.to_datetime(df['publishDate'])

# # Create a new column 'yearOfPublication' with the year of publication
# df['yearOfPublication'] = df['publishDate'].dt.year

# # Print the updated DataFrame
# print(df)




# from dateutil import parser

# # Assuming your data is stored in a DataFrame called 'df'
# # You can read your data into the DataFrame using pandas, for example:
# # df = pd.read_csv('your_data.csv')

# # Convert 'publishDate' column to datetime format with custom date parsing
# df['publishDate'] = df['publishDate'].apply(lambda x: parser.parse(x).date() if pd.notnull(x) else None)

# # Create a new column 'yearOfPublication' with the year of publication
# df['yearOfPublication'] = df['publishDate'].dt.year

# # Print the updated DataFrame
# print(df)






# Assuming your data is stored in a DataFrame called 'df'
# You can read your data into the DataFrame using pandas, for example:
# df = pd.read_csv('your_data.csv')

# # Convert 'publishDate' column to datetime format with custom date format
df['publishDate'] = pd.to_datetime(df['publishDate'], format='%m/%d/%y')

# # Create a new column 'yearOfPublication' with the year of publication
df['yearOfPublication'] = df['publishDate'].dt.year

# # Print the updated DataFrame
print(df)

ValueError: time data 'February 18th 2002' does not match format '%m/%d/%y' (match)